import { FileItem, DocumentCategory, FileType, EvidenceStatus, FileVisibility } from "@/types/documents";

export const mockFileItems: FileItem[] = [
  {
    id: "1",
    nomeArquivo: "Contrato_EmpresaABC_2024.pdf",
    nomeExibicao: "Empresa ABC_Otimização de Compras_Contratos_2024-12-10_Contrato Principal",
    clienteId: "client-1",
    clienteNome: "Empresa ABC",
    projetoId: "project-1",
    projetoNome: "Otimização de Compras",
    categoriaId: "contracts",
    tags: ["Contrato", "Compras"],
    tipo: "Documento",
    visibilidade: "Ambos",
    vinculos: {},
    tamanhoBytes: 250880,
    mimeType: "application/pdf",
    uploadedAt: "2024-12-10T10:00:00Z",
    uploadedBy: "admin",
  },
  {
    id: "2",
    nomeArquivo: "Diagnóstico_Compras_Final.xlsx",
    nomeExibicao: "Empresa ABC_Otimização de Compras_Diagnósticos_2024-11-15_Análise Final",
    clienteId: "client-1",
    clienteNome: "Empresa ABC",
    projetoId: "project-1",
    projetoNome: "Otimização de Compras",
    categoriaId: "diagnostics",
    tags: ["Compras", "KPI"],
    tipo: "Documento",
    visibilidade: "Interno",
    vinculos: { diagnosticId: "diag-1" },
    tamanhoBytes: 1258291,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    uploadedAt: "2024-11-15T14:30:00Z",
    uploadedBy: "analista",
  },
  {
    id: "3",
    nomeArquivo: "Indicadores_Novembro.xlsx",
    nomeExibicao: "Indústria XYZ_Gestão de Estoque_Indicadores_2024-12-01_Novembro",
    clienteId: "client-2",
    clienteNome: "Indústria XYZ",
    projetoId: "project-2",
    projetoNome: "Gestão de Estoque",
    categoriaId: "indicators",
    tags: ["Estoque", "KPI"],
    tipo: "Documento",
    visibilidade: "Cliente",
    vinculos: {},
    tamanhoBytes: 911360,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    uploadedAt: "2024-12-01T09:00:00Z",
    uploadedBy: "gestor",
  },
  {
    id: "4",
    nomeArquivo: "Ata_Reuniao_16Dez.docx",
    nomeExibicao: "Serviços JKL_Processos de Vendas_Reuniões_2024-12-16_Ata Kickoff",
    clienteId: "client-3",
    clienteNome: "Serviços JKL",
    projetoId: "project-3",
    projetoNome: "Processos de Vendas",
    categoriaId: "meetings",
    tags: ["Reunião", "Vendas"],
    tipo: "Documento",
    visibilidade: "Ambos",
    vinculos: { meetingId: "meeting-1" },
    tamanhoBytes: 159744,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    uploadedAt: "2024-12-16T16:00:00Z",
    uploadedBy: "admin",
  },
  {
    id: "5",
    nomeArquivo: "Evidencia_Compra_Aprovada.png",
    nomeExibicao: "Empresa ABC_Otimização de Compras_Evidências_2024-12-12_Cotação Aprovada",
    clienteId: "client-1",
    clienteNome: "Empresa ABC",
    projetoId: "project-1",
    projetoNome: "Otimização de Compras",
    categoriaId: "evidence",
    tags: ["Compras", "Processos"],
    tipo: "Evidência",
    statusEvidencia: "Aprovada",
    visibilidade: "Interno",
    vinculos: { taskId: "task-1" },
    tamanhoBytes: 524288,
    mimeType: "image/png",
    uploadedAt: "2024-12-12T11:00:00Z",
    uploadedBy: "analista",
  },
  {
    id: "6",
    nomeArquivo: "Evidencia_Reuniao_Pendente.pdf",
    nomeExibicao: "Indústria XYZ_Gestão de Estoque_Evidências_2024-12-14_Registro Reunião",
    clienteId: "client-2",
    clienteNome: "Indústria XYZ",
    projetoId: "project-2",
    projetoNome: "Gestão de Estoque",
    categoriaId: "evidence",
    tags: ["Reunião", "Estoque"],
    tipo: "Evidência",
    statusEvidencia: "Pendente",
    visibilidade: "Interno",
    vinculos: { meetingId: "meeting-2" },
    tamanhoBytes: 307200,
    mimeType: "application/pdf",
    uploadedAt: "2024-12-14T10:30:00Z",
    uploadedBy: "gestor",
  },
  {
    id: "7",
    nomeArquivo: "Evidencia_Treinamento_Rejeitada.jpg",
    nomeExibicao: "Serviços JKL_Processos de Vendas_Evidências_2024-12-13_Treinamento Equipe",
    clienteId: "client-3",
    clienteNome: "Serviços JKL",
    projetoId: "project-3",
    projetoNome: "Processos de Vendas",
    categoriaId: "evidence",
    tags: ["Treinamento", "Vendas"],
    tipo: "Evidência",
    statusEvidencia: "Rejeitada",
    motivoRejeicao: "Imagem não mostra participantes identificados",
    visibilidade: "Interno",
    vinculos: { taskId: "task-2" },
    tamanhoBytes: 819200,
    mimeType: "image/jpeg",
    uploadedAt: "2024-12-13T15:00:00Z",
    uploadedBy: "analista",
  },
  {
    id: "8",
    nomeArquivo: "POP_Vendas_v2.pdf",
    nomeExibicao: "Serviços JKL_Processos de Vendas_Processos_2024-12-08_POP Atendimento",
    clienteId: "client-3",
    clienteNome: "Serviços JKL",
    projetoId: "project-3",
    projetoNome: "Processos de Vendas",
    categoriaId: "processes",
    tags: ["Vendas", "Processos"],
    tipo: "Documento",
    visibilidade: "Cliente",
    vinculos: {},
    tamanhoBytes: 1048576,
    mimeType: "application/pdf",
    uploadedAt: "2024-12-08T09:00:00Z",
    uploadedBy: "admin",
  },
  {
    id: "9",
    nomeArquivo: "Manual_Sistema_Estoque.pdf",
    nomeExibicao: "Indústria XYZ_Gestão de Estoque_Treinamento_2024-12-05_Manual Sistema",
    clienteId: "client-2",
    clienteNome: "Indústria XYZ",
    projetoId: "project-2",
    projetoNome: "Gestão de Estoque",
    categoriaId: "training",
    tags: ["Treinamento", "Estoque"],
    tipo: "Documento",
    visibilidade: "Ambos",
    vinculos: {},
    tamanhoBytes: 2097152,
    mimeType: "application/pdf",
    uploadedAt: "2024-12-05T11:00:00Z",
    uploadedBy: "gestor",
  },
  {
    id: "10",
    nomeArquivo: "Arquivo_Sem_Vinculo.pdf",
    nomeExibicao: "Documento sem vínculo",
    categoriaId: "processes",
    tags: ["Processos"],
    tipo: "Documento",
    visibilidade: "Interno",
    vinculos: {},
    tamanhoBytes: 204800,
    mimeType: "application/pdf",
    uploadedAt: "2024-12-17T08:00:00Z",
    uploadedBy: "admin",
  },
  {
    id: "11",
    nomeArquivo: "Evidencia_Sem_Projeto.png",
    nomeExibicao: "Evidência sem projeto vinculado",
    categoriaId: "evidence",
    tags: [],
    tipo: "Evidência",
    statusEvidencia: "Pendente",
    visibilidade: "Interno",
    vinculos: {},
    tamanhoBytes: 409600,
    mimeType: "image/png",
    uploadedAt: "2024-12-17T14:00:00Z",
    uploadedBy: "analista",
  },
];

export const mockClients = [
  { id: "client-1", name: "Empresa ABC" },
  { id: "client-2", name: "Indústria XYZ" },
  { id: "client-3", name: "Serviços JKL" },
];

export const mockProjects = [
  { id: "project-1", name: "Otimização de Compras", clientId: "client-1" },
  { id: "project-2", name: "Gestão de Estoque", clientId: "client-2" },
  { id: "project-3", name: "Processos de Vendas", clientId: "client-3" },
  { id: "project-4", name: "Melhoria Contínua", clientId: "client-1" },
];

export const mockTasks = [
  { id: "task-1", title: "Revisar cotações de fornecedores", projectId: "project-1" },
  { id: "task-2", title: "Treinar equipe de vendas", projectId: "project-3" },
  { id: "task-3", title: "Atualizar sistema de estoque", projectId: "project-2" },
];

export const mockDiagnostics = [
  { id: "diag-1", name: "Diagnóstico de Compras", projectId: "project-1" },
  { id: "diag-2", name: "Análise de Estoque", projectId: "project-2" },
];

export const mockMeetings = [
  { id: "meeting-1", title: "Kickoff Processos de Vendas", projectId: "project-3" },
  { id: "meeting-2", title: "Alinhamento Semanal Estoque", projectId: "project-2" },
];
