import { useEffect, useMemo, useState } from "react";
import { Check, ExternalLink, Plus } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { addCommercialActivity, completeCommercialFollowUp, convertLeadToClient, findLeadClientDuplicates, saveCommercialProposal, scheduleCommercialFollowUp, type ClientDuplicate, type CommercialActivity, type CommercialFollowUp, type CommercialLead, type CommercialProposal } from "@/integrations/supabase/commercial";
import { proposalStatuses, proposalStatusLabels, type ProposalStatus } from "@/lib/commercial/commercial";
import { toast } from "sonner";

type Props = { open: boolean; onOpenChange: (open: boolean) => void; lead: CommercialLead | null; activities: CommercialActivity[]; proposals: CommercialProposal[]; followUps: CommercialFollowUp[]; employees: Array<{ userId?: string; name: string }>; userId: string; canWrite: boolean; onReload: () => Promise<void>; onCreateProject: (lead: CommercialLead, clientId: string) => void };
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const displayDate = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));

export function CommercialDetailsDialog({ open, onOpenChange, lead, activities, proposals, followUps, employees, userId, canWrite, onReload, onCreateProject }: Props) {
  const [busy, setBusy] = useState(false);
  const [activity, setActivity] = useState({ activity_type: "note", title: "", description: "" });
  const [proposal, setProposal] = useState({ value: 0, scope: "", proposal_date: new Date().toISOString().slice(0, 10), valid_until: "", status: "draft" as ProposalStatus });
  const [followUp, setFollowUp] = useState({ action: "", due_at: "", responsible_user_id: userId });
  const [duplicates, setDuplicates] = useState<ClientDuplicate[]>([]);
  const [checkedDuplicates, setCheckedDuplicates] = useState(false);
  const timeline = useMemo(() => activities.filter((item) => item.lead_id === lead?.id), [activities, lead?.id]);
  const leadProposals = useMemo(() => proposals.filter((item) => item.lead_id === lead?.id), [proposals, lead?.id]);
  const leadFollowUps = useMemo(() => followUps.filter((item) => item.lead_id === lead?.id), [followUps, lead?.id]);

  useEffect(() => { if (open) { setCheckedDuplicates(false); setDuplicates([]); setFollowUp((current) => ({ ...current, responsible_user_id: lead?.responsible_user_id || userId })); } }, [lead?.responsible_user_id, open, userId]);
  if (!lead) return null;

  async function perform(action: () => Promise<unknown>, success: string) { setBusy(true); try { await action(); await onReload(); toast.success(success); } catch (error) { toast.error(error instanceof Error ? error.message : "Operação não concluída."); } finally { setBusy(false); } }
  async function registerActivity(event: React.FormEvent) { event.preventDefault(); if (!activity.title.trim()) return; await perform(() => addCommercialActivity({ workspace_id: lead.workspace_id, lead_id: lead.id, activity_type: activity.activity_type, title: activity.title.trim(), description: activity.description || null, created_by: userId }), "Atividade registrada."); setActivity({ activity_type: "note", title: "", description: "" }); }
  async function registerProposal(event: React.FormEvent) { event.preventDefault(); if (!proposal.scope.trim()) return toast.error("Informe o escopo da proposta."); await perform(() => saveCommercialProposal({ workspace_id: lead.workspace_id, lead_id: lead.id, value: proposal.value, scope: proposal.scope.trim(), proposal_date: proposal.proposal_date, valid_until: proposal.valid_until || null, status: proposal.status, created_by: userId }), "Proposta registrada."); setProposal({ value: 0, scope: "", proposal_date: new Date().toISOString().slice(0, 10), valid_until: "", status: "draft" }); }
  async function changeProposalStatus(item: CommercialProposal, status: ProposalStatus) { await perform(() => saveCommercialProposal({ ...item, status }), "Status da proposta atualizado."); }
  async function registerFollowUp(event: React.FormEvent) { event.preventDefault(); if (!followUp.action.trim() || !followUp.due_at || !followUp.responsible_user_id) return toast.error("Preencha ação, data e responsável."); await perform(() => scheduleCommercialFollowUp(lead.id, followUp.action.trim(), new Date(followUp.due_at).toISOString(), followUp.responsible_user_id), "Próximo contato agendado."); setFollowUp((current) => ({ ...current, action: "", due_at: "" })); }
  async function checkDuplicates() { setBusy(true); try { setDuplicates(await findLeadClientDuplicates(lead.id)); setCheckedDuplicates(true); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha ao verificar clientes."); } finally { setBusy(false); } }
  async function convert(existingClientId?: string) { await perform(async () => { const clientId = await convertLeadToClient(lead.id, existingClientId); onCreateProject({ ...lead, converted_client_id: clientId }, clientId); }, "Cliente vinculado à oportunidade."); }

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{lead.company}</DialogTitle><DialogDescription>{lead.name} · {lead.service || "Serviço não informado"} · {money.format(Number(lead.value || 0))}</DialogDescription></DialogHeader>
    <Tabs defaultValue="history"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="history">Histórico</TabsTrigger><TabsTrigger value="proposals">Propostas</TabsTrigger><TabsTrigger value="follow-up">Follow-up</TabsTrigger><TabsTrigger value="conversion">Conversão</TabsTrigger></TabsList>
      <TabsContent value="history" className="space-y-4">{canWrite && <form onSubmit={registerActivity} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-3"><div><Label>Tipo</Label><Select value={activity.activity_type} onValueChange={(activity_type) => setActivity({ ...activity, activity_type })}><SelectTrigger aria-label="Tipo de atividade"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="call">Ligação</SelectItem><SelectItem value="message">Mensagem</SelectItem><SelectItem value="meeting">Reunião</SelectItem><SelectItem value="note">Observação</SelectItem></SelectContent></Select></div><div className="sm:col-span-2"><Label htmlFor="activity-title">Resumo</Label><Input id="activity-title" value={activity.title} onChange={(e) => setActivity({ ...activity, title: e.target.value })} /></div><div className="sm:col-span-3"><Label htmlFor="activity-description">Detalhes</Label><Textarea id="activity-description" rows={2} value={activity.description} onChange={(e) => setActivity({ ...activity, description: e.target.value })} /></div><Button disabled={busy} className="sm:col-start-3"><Plus className="mr-2 h-4 w-4" />Registrar</Button></form>}
        <div className="space-y-2">{timeline.length ? timeline.map((item) => <div key={item.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{item.title}</p><Badge variant="outline">{item.activity_type}</Badge></div>{item.description && <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}<p className="mt-2 text-xs text-muted-foreground">{displayDate(item.happened_at)}</p></div>) : <Empty text="Nenhuma atividade registrada." />}</div>
      </TabsContent>
      <TabsContent value="proposals" className="space-y-4">{canWrite && <form onSubmit={registerProposal} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-2"><Field label="Valor" id="proposal-value"><Input id="proposal-value" type="number" min="0" value={proposal.value} onChange={(e) => setProposal({ ...proposal, value: Number(e.target.value) })} /></Field><div><Label>Status</Label><Select value={proposal.status} onValueChange={(status: ProposalStatus) => setProposal({ ...proposal, status })}><SelectTrigger aria-label="Status da proposta"><SelectValue /></SelectTrigger><SelectContent>{proposalStatuses.map((status) => <SelectItem key={status} value={status}>{proposalStatusLabels[status]}</SelectItem>)}</SelectContent></Select></div><Field label="Data" id="proposal-date"><Input id="proposal-date" type="date" value={proposal.proposal_date} onChange={(e) => setProposal({ ...proposal, proposal_date: e.target.value })} /></Field><Field label="Validade" id="proposal-valid"><Input id="proposal-valid" type="date" value={proposal.valid_until} onChange={(e) => setProposal({ ...proposal, valid_until: e.target.value })} /></Field><div className="sm:col-span-2"><Label htmlFor="proposal-scope">Escopo</Label><Textarea id="proposal-scope" value={proposal.scope} onChange={(e) => setProposal({ ...proposal, scope: e.target.value })} /></div><Button disabled={busy} className="sm:col-start-2">Registrar proposta</Button></form>}
        <div className="space-y-2">{leadProposals.map((item) => <div key={item.id} className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{money.format(Number(item.value))}</p><p className="text-sm text-muted-foreground line-clamp-2">{item.scope}</p></div>{canWrite ? <Select value={item.status} onValueChange={(status: ProposalStatus) => void changeProposalStatus(item, status)}><SelectTrigger className="w-full sm:w-44" aria-label={`Status da proposta de ${money.format(Number(item.value))}`}><SelectValue /></SelectTrigger><SelectContent>{proposalStatuses.map((status) => <SelectItem key={status} value={status}>{proposalStatusLabels[status]}</SelectItem>)}</SelectContent></Select> : <Badge>{proposalStatusLabels[item.status]}</Badge>}</div>)}</div>
      </TabsContent>
      <TabsContent value="follow-up" className="space-y-4">{canWrite && <form onSubmit={registerFollowUp} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label htmlFor="followup-action">Próximo contato</Label><Input id="followup-action" value={followUp.action} onChange={(e) => setFollowUp({ ...followUp, action: e.target.value })} placeholder="Ligar para revisar a proposta" /></div><Field label="Data e hora" id="followup-date"><Input id="followup-date" type="datetime-local" value={followUp.due_at} onChange={(e) => setFollowUp({ ...followUp, due_at: e.target.value })} /></Field><div><Label>Responsável</Label><Select value={followUp.responsible_user_id} onValueChange={(responsible_user_id) => setFollowUp({ ...followUp, responsible_user_id })}><SelectTrigger aria-label="Responsável pelo follow-up"><SelectValue /></SelectTrigger><SelectContent>{employees.filter((employee) => employee.userId).map((employee) => <SelectItem key={employee.userId} value={employee.userId!}>{employee.name}</SelectItem>)}</SelectContent></Select></div><Button disabled={busy} className="sm:col-start-2">Agendar</Button></form>}
        <div className="space-y-2">{leadFollowUps.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div><p className={item.completed_at ? "line-through text-muted-foreground" : "font-medium"}>{item.action}</p><p className="text-xs text-muted-foreground">{displayDate(item.due_at)}</p></div>{!item.completed_at && <Button size="sm" variant="outline" disabled={busy} onClick={() => perform(() => completeCommercialFollowUp(item.id), "Follow-up concluído.")}><Check className="mr-2 h-4 w-4" />Concluir</Button>}</div>)}</div>
      </TabsContent>
      <TabsContent value="conversion" className="space-y-4"><div className="rounded-lg border p-4"><p className="font-medium">Cliente e projeto</p><p className="mt-1 text-sm text-muted-foreground">A conversão só é liberada em oportunidades ganhas e sempre verifica possíveis clientes existentes.</p></div>
        {!canWrite ? <Empty text="A conversão exige papel de gestor do workspace." /> : lead.stage !== "won" ? <Empty text="Marque a oportunidade como ganha para iniciar a conversão." /> : lead.converted_client_id ? <div className="space-y-3"><Badge variant="secondary">Cliente vinculado</Badge><Button onClick={() => onCreateProject(lead, lead.converted_client_id!)}><ExternalLink className="mr-2 h-4 w-4" />Criar projeto usando modelo</Button></div> : <div className="space-y-3"><Button variant="outline" disabled={busy} onClick={checkDuplicates}>Verificar clientes existentes</Button>{checkedDuplicates && (duplicates.length ? <div className="space-y-2"><p className="text-sm font-medium">Possíveis duplicidades encontradas</p>{duplicates.map((client) => <div key={client.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{client.trade_name || client.name}</p><p className="text-xs text-muted-foreground">{client.contact_email || client.contact_phone || "Sem contato"}</p></div><Button size="sm" disabled={busy} onClick={() => convert(client.id)}>Usar este cliente</Button></div>)}</div> : <Button disabled={busy} onClick={() => convert()}>Criar novo cliente</Button>)}</div>}
      </TabsContent>
    </Tabs>
  </DialogContent></Dialog>;
}

function Field({ label, id, children }: { label: string; id: string; children: React.ReactNode }) { return <div><Label htmlFor={id}>{label}</Label>{children}</div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed p-5 text-center text-sm text-muted-foreground">{text}</div>; }
