import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clipboard, FileDown, History, Printer, Save, Share2, Sparkles } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useData } from "@/contexts/DataContext";
import { createReportVersion, getConsultingReport, listReportVersions, REPORT_SECTIONS, sectionToText, updateConsultingReport, ConsultingReportRow } from "@/lib/consulting-reports";
import { exportConsultingReportPdf } from "@/lib/consulting-report-pdf";
import type { Json } from "@/integrations/supabase/types";

export default function ConsultingReportDetail() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { clients } = useData();
  const [report, setReport] = useState<ConsultingReportRow | null>(null); const [versions, setVersions] = useState<ConsultingReportRow[]>([]); const [title, setTitle] = useState(""); const [sections, setSections] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; getConsultingReport(id).then((data) => { setReport(data); setTitle(data.title); const source = data.sections as Record<string, Json | undefined>; setSections(Object.fromEntries(REPORT_SECTIONS.map(([key]) => [key, sectionToText(source[key])]))); return listReportVersions(data.version_group_id); }).then(setVersions).catch((error) => toast.error((error as Error).message)); }, [id]);
  const clientName = useMemo(() => { const client = clients.find((item) => item.id === report?.client_id); return client?.nomeFantasia || client?.razaoSocial || client?.name || "Cliente"; }, [clients, report?.client_id]);
  if (!report) return <p className="text-muted-foreground">Carregando relatório…</p>;
  const reportText = () => [title, `${clientName} · ${report.period_start} a ${report.period_end}`, ...REPORT_SECTIONS.flatMap(([key, label]) => [`\n${label}`, sections[key] || ""])].join("\n");
  const save = async (finalize = false) => { if (finalize && !window.confirm("Finalizar esta versão? Depois disso, alterações exigirão uma nova versão.")) return; setSaving(true); try { await updateConsultingReport(report.id, title, sections, finalize); setReport((current) => current ? { ...current, title, sections: sections as unknown as Json, status: finalize ? "finalized" : current.status } : current); toast.success(finalize ? "Relatório finalizado." : "Rascunho salvo."); } catch (error) { toast.error((error as Error).message); } finally { setSaving(false); } };
  const copy = async () => { await navigator.clipboard.writeText(reportText()); toast.success("Relatório copiado."); };
  const share = async () => { try { if (navigator.share) { await navigator.share({ title, text: reportText() }); return; } await copy(); toast.info("Compartilhamento nativo indisponível; o relatório foi copiado."); } catch (error) { if ((error as DOMException).name !== "AbortError") toast.error("Não foi possível compartilhar o relatório."); } };
  const newVersion = async () => { setSaving(true); try { const nextId = await createReportVersion(report.id); navigate(`/relatorios/consultoria/${nextId}`); } catch (error) { toast.error((error as Error).message); setSaving(false); } };
  const exportPdf = async () => { try { await exportConsultingReportPdf({ ...report, title, sections: sections as unknown as Json }, clientName); toast.success("PDF exportado."); } catch { toast.error("Não foi possível exportar o PDF."); } };
  return <div className="space-y-6 print:bg-white"><header className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold">Relatório de Consultoria</h1><Badge variant={report.status === "finalized" ? "default" : "secondary"}>{report.status === "finalized" ? "Finalizado" : "Rascunho"}</Badge></div><p className="text-muted-foreground">{clientName} · versão {report.version_number} · {new Date(report.period_start + "T12:00:00").toLocaleDateString("pt-BR")} a {new Date(report.period_end + "T12:00:00").toLocaleDateString("pt-BR")}</p></div><div className="flex flex-wrap gap-2 print:hidden"><Button asChild variant="outline"><Link to={`/assistente?reportId=${report.id}&auto=1&prompt=${encodeURIComponent("Melhore a redação deste relatório, proponha um resumo executivo e destaque riscos e pontos importantes sem alterar os dados estruturados.")}`}><Sparkles className="mr-2 h-4 w-4" />Aprimorar com IA</Link></Button><Button variant="outline" onClick={() => void copy()}><Clipboard className="mr-2 h-4 w-4" />Copiar</Button><Button variant="outline" onClick={() => void share()}><Share2 className="mr-2 h-4 w-4" />Compartilhar</Button><Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Imprimir</Button><Button variant="outline" onClick={() => void exportPdf()}><FileDown className="mr-2 h-4 w-4" />Exportar PDF</Button>{report.status === "finalized" ? <Button onClick={() => void newVersion()} disabled={saving}><History className="mr-2 h-4 w-4" />Nova versão</Button> : <><Button variant="outline" onClick={() => void save()} disabled={saving}><Save className="mr-2 h-4 w-4" />Salvar</Button><Button onClick={() => void save(true)} disabled={saving}><CheckCircle2 className="mr-2 h-4 w-4" />Finalizar</Button></>}</div></header>
    <Card><CardContent className="space-y-2 pt-6"><Label htmlFor="report-title">Título</Label><Input id="report-title" value={title} disabled={report.status === "finalized"} onChange={(event) => setTitle(event.target.value)} /></CardContent></Card>
    <div className="space-y-4">{REPORT_SECTIONS.map(([key, label]) => <Card key={key}><CardHeader><CardTitle className="text-lg">{label}</CardTitle></CardHeader><CardContent><Textarea aria-label={label} value={sections[key] || ""} disabled={report.status === "finalized"} onChange={(event) => setSections((current) => ({ ...current, [key]: event.target.value }))} rows={Math.max(3, Math.min(12, (sections[key]?.split("\n").length || 1) + 1))} className="print:min-h-0 print:resize-none print:border-0 print:p-0" /></CardContent></Card>)}</div>
    <Card className="print:hidden"><CardHeader><CardTitle className="text-base">Histórico de versões</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{versions.map((version) => <Button key={version.id} variant={version.id === report.id ? "default" : "outline"} size="sm" onClick={() => navigate(`/relatorios/consultoria/${version.id}`)}>v{version.version_number} · {version.status === "finalized" ? "final" : "rascunho"}</Button>)}</CardContent></Card>
  </div>;
}
