import { useEffect, useState } from "react";
import { Layers3, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { listProjectTemplates, listStandaloneTaskTemplates, ProjectTemplateSummary, saveProjectTemplate, saveStandaloneTaskTemplate, StandaloneTaskTemplate, TemplateStageInput, TemplateTaskInput } from "@/lib/project-templates";
import { useData } from "@/contexts/DataContext";

const blankStage = (position: number): TemplateStageInput => ({ title: "", description: "", position });
const blankTask = (position: number): TemplateTaskInput => ({ title: "", stagePosition: 0, priority: "medium", startOffsetDays: 0, dueOffsetDays: 3, initialStatus: "not_started", evidenceRequired: false, position, checklist: [] });

export default function ProjectTemplates() {
  const { employees } = useData();
  const [templates, setTemplates] = useState<ProjectTemplateSummary[]>([]);
  const [taskTemplates, setTaskTemplates] = useState<StandaloneTaskTemplate[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [taskOpen, setTaskOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [internal, setInternal] = useState(false);
  const [status, setStatus] = useState<"draft" | "published">("published");
  const [stages, setStages] = useState<TemplateStageInput[]>([blankStage(0)]);
  const [tasks, setTasks] = useState<TemplateTaskInput[]>([blankTask(0)]);
  const [standalone, setStandalone] = useState({ title: "", description: "", priority: "medium" as TemplateTaskInput["priority"], startOffsetDays: 0, dueOffsetDays: 7, initialStatus: "not_started" as TemplateTaskInput["initialStatus"], defaultAssigneeId: "", checklist: "" });

  const load = async () => { setLoading(true); try { const [projects, standaloneTasks] = await Promise.all([listProjectTemplates(), listStandaloneTaskTemplates()]); setTemplates(projects); setTaskTemplates(standaloneTasks); } catch (error) { toast.error((error as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const reset = () => { setName(""); setDescription(""); setInternal(false); setStatus("published"); setStages([blankStage(0)]); setTasks([blankTask(0)]); };
  const updateTask = (index: number, patch: Partial<TemplateTaskInput>) => setTasks((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));

  const save = async () => {
    if (!name.trim() || stages.some((stage) => !stage.title.trim()) || tasks.some((task) => !task.title.trim())) { toast.error("Preencha o nome do modelo, das etapas e das tarefas."); return; }
    if (tasks.some((task) => task.dueOffsetDays < task.startOffsetDays)) { toast.error("O prazo final não pode ser anterior ao início relativo."); return; }
    setSaving(true);
    try {
      await saveProjectTemplate({ name, description, projectType: "consulting", defaultPhase: stages[0].title, isInternalProcess: internal, status, stages, tasks });
      toast.success("Modelo salvo com estrutura reutilizável."); setOpen(false); reset(); await load();
    } catch (error) { toast.error((error as Error).message); } finally { setSaving(false); }
  };

  const saveTaskTemplate = async () => {
    if (!standalone.title.trim() || standalone.dueOffsetDays < standalone.startOffsetDays) { toast.error("Informe um título e prazos relativos válidos."); return; }
    setSaving(true);
    try { await saveStandaloneTaskTemplate({ ...standalone, checklist: standalone.checklist.split(";").map((text, position) => ({ text: text.trim(), position })).filter((item) => item.text) }); toast.success("Modelo de tarefa salvo."); setTaskOpen(false); setStandalone({ title: "", description: "", priority: "medium", startOffsetDays: 0, dueOffsetDays: 7, initialStatus: "not_started", defaultAssigneeId: "", checklist: "" }); await load(); }
    catch (error) { toast.error((error as Error).message); } finally { setSaving(false); }
  };

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold">Modelos de projeto</h1><p className="text-muted-foreground">Estruturas reutilizáveis de etapas, tarefas, checklists e prazos relativos.</p></div><Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Novo modelo</Button></div>
    {loading ? <p className="text-sm text-muted-foreground" aria-live="polite">Carregando modelos…</p> : templates.length === 0 ? <Card><CardContent className="py-12 text-center text-muted-foreground">Nenhum modelo cadastrado.</CardContent></Card> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates.map((template) => <Card key={template.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{template.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{template.description}</p></div><Badge variant={template.status === "published" ? "default" : "secondary"}>{template.status === "published" ? "Publicado" : template.status === "draft" ? "Rascunho" : "Arquivado"}</Badge></div></CardHeader><CardContent className="flex items-center justify-between text-sm"><span>{template.stageCount} etapas · {template.taskCount} tarefas</span>{template.isInternalProcess && <Badge variant="outline">Processo interno</Badge>}</CardContent></Card>)}</div>}
    <section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Modelos de tarefa</h2><p className="text-sm text-muted-foreground">Blocos menores reutilizáveis em qualquer nova tarefa.</p></div><Button variant="outline" onClick={() => setTaskOpen(true)}><Plus className="mr-2 h-4 w-4" />Modelo de tarefa</Button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{taskTemplates.map((template) => <Card key={template.id}><CardHeader><CardTitle className="text-base">{template.title}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Prazo: dia +{template.dueOffsetDays} · {template.checklist.length} itens</CardContent></Card>)}</div></section>
    <Dialog open={open} onOpenChange={(value) => { setOpen(value); if (!value) reset(); }}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Novo modelo de projeto</DialogTitle><DialogDescription>Dia 0 é a data inicial do projeto; use +3, +7 ou +15 para planejar as tarefas.</DialogDescription></DialogHeader>
      <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="template-name">Nome</Label><Input id="template-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Consultoria Empresarial" /></div><div className="flex items-end gap-3 pb-2"><Switch id="internal-process" checked={internal} onCheckedChange={setInternal} /><Label htmlFor="internal-process">Processo interno</Label></div></div><div className="space-y-2"><Label htmlFor="template-description">Descrição</Label><Textarea id="template-description" value={description} onChange={(event) => setDescription(event.target.value)} /></div>
        <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-medium">Etapas</h2><Button type="button" size="sm" variant="outline" onClick={() => setStages((items) => [...items, blankStage(items.length)])}><Plus className="mr-1 h-3 w-3" />Etapa</Button></div>{stages.map((stage, index) => <div key={stage.position} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_1fr_auto]"><Input aria-label={`Nome da etapa ${index + 1}`} value={stage.title} onChange={(event) => setStages((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} placeholder="Nome da etapa" /><Input aria-label={`Descrição da etapa ${index + 1}`} value={stage.description} onChange={(event) => setStages((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item))} placeholder="Descrição" /><Button type="button" size="icon" variant="ghost" disabled={stages.length === 1} onClick={() => setStages((items) => items.filter((_, itemIndex) => itemIndex !== index).map((item, position) => ({ ...item, position })))} aria-label={`Remover etapa ${index + 1}`}><Trash2 className="h-4 w-4" /></Button></div>)}</section>
        <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-medium">Tarefas padrão</h2><Button type="button" size="sm" variant="outline" onClick={() => setTasks((items) => [...items, blankTask(items.length)])}><Plus className="mr-1 h-3 w-3" />Tarefa</Button></div>{tasks.map((task, index) => <div key={task.position} className="space-y-3 rounded-lg border p-3"><div className="flex gap-2"><Input aria-label={`Nome da tarefa ${index + 1}`} value={task.title} onChange={(event) => updateTask(index, { title: event.target.value })} placeholder="Nome da tarefa" /><Button type="button" size="icon" variant="ghost" disabled={tasks.length === 1} onClick={() => setTasks((items) => items.filter((_, itemIndex) => itemIndex !== index).map((item, position) => ({ ...item, position })))} aria-label={`Remover tarefa ${index + 1}`}><Trash2 className="h-4 w-4" /></Button></div><div className="grid gap-3 sm:grid-cols-4"><Select value={String(task.stagePosition)} onValueChange={(value) => updateTask(index, { stagePosition: Number(value) })}><SelectTrigger aria-label={`Etapa da tarefa ${index + 1}`}><SelectValue /></SelectTrigger><SelectContent>{stages.map((stage) => <SelectItem key={stage.position} value={String(stage.position)}>{stage.title || `Etapa ${stage.position + 1}`}</SelectItem>)}</SelectContent></Select><Select value={task.priority} onValueChange={(value: TemplateTaskInput["priority"]) => updateTask(index, { priority: value })}><SelectTrigger aria-label={`Prioridade da tarefa ${index + 1}`}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="low">Baixa</SelectItem><SelectItem value="medium">Média</SelectItem><SelectItem value="high">Alta</SelectItem><SelectItem value="urgent">Urgente</SelectItem></SelectContent></Select><div><Label className="text-xs">Início (dias)</Label><Input type="number" value={task.startOffsetDays} onChange={(event) => updateTask(index, { startOffsetDays: Number(event.target.value) })} /></div><div><Label className="text-xs">Prazo (dias)</Label><Input type="number" value={task.dueOffsetDays} onChange={(event) => updateTask(index, { dueOffsetDays: Number(event.target.value) })} /></div></div><Input aria-label={`Checklist da tarefa ${index + 1}`} value={task.checklist.map((item) => item.text).join("; ")} onChange={(event) => updateTask(index, { checklist: event.target.value.split(";").map((text, position) => ({ text: text.trim(), position })).filter((entry) => entry.text) })} placeholder="Checklist separado por ponto e vírgula" /></div>)}</section>
        <div className="space-y-2"><Label>Status</Label><Select value={status} onValueChange={(value: "draft" | "published") => setStatus(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="published">Publicado</SelectItem><SelectItem value="draft">Rascunho</SelectItem></SelectContent></Select></div></div>
      <DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => void save()} disabled={saving}><Layers3 className="mr-2 h-4 w-4" />{saving ? "Salvando…" : "Salvar modelo"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={taskOpen} onOpenChange={setTaskOpen}><DialogContent><DialogHeader><DialogTitle>Novo modelo de tarefa</DialogTitle><DialogDescription>Crie um bloco menor para preencher novas tarefas com um clique.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label htmlFor="standalone-title">Título</Label><Input id="standalone-title" value={standalone.title} onChange={(event) => setStandalone((current) => ({ ...current, title: event.target.value }))} placeholder="Ex.: Auditoria Financeira" /></div><div className="space-y-2"><Label htmlFor="standalone-description">Descrição</Label><Textarea id="standalone-description" value={standalone.description} onChange={(event) => setStandalone((current) => ({ ...current, description: event.target.value }))} /></div><div className="grid gap-3 sm:grid-cols-3"><div><Label>Prioridade</Label><Select value={standalone.priority} onValueChange={(priority: TemplateTaskInput["priority"]) => setStandalone((current) => ({ ...current, priority }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="low">Baixa</SelectItem><SelectItem value="medium">Média</SelectItem><SelectItem value="high">Alta</SelectItem><SelectItem value="urgent">Urgente</SelectItem></SelectContent></Select></div><div><Label htmlFor="standalone-start">Início (dias)</Label><Input id="standalone-start" type="number" value={standalone.startOffsetDays} onChange={(event) => setStandalone((current) => ({ ...current, startOffsetDays: Number(event.target.value) }))} /></div><div><Label htmlFor="standalone-due">Prazo (dias)</Label><Input id="standalone-due" type="number" value={standalone.dueOffsetDays} onChange={(event) => setStandalone((current) => ({ ...current, dueOffsetDays: Number(event.target.value) }))} /></div></div><div className="space-y-2"><Label>Responsável padrão</Label><Select value={standalone.defaultAssigneeId || "none"} onValueChange={(value) => setStandalone((current) => ({ ...current, defaultAssigneeId: value === "none" ? "" : value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Definir ao aplicar</SelectItem>{employees.filter((employee) => employee.status === "active" && employee.userId).map((employee) => <SelectItem key={employee.userId} value={employee.userId!}>{employee.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="standalone-checklist">Checklist</Label><Input id="standalone-checklist" value={standalone.checklist} onChange={(event) => setStandalone((current) => ({ ...current, checklist: event.target.value }))} placeholder="Itens separados por ponto e vírgula" /></div></div><DialogFooter><Button variant="outline" onClick={() => setTaskOpen(false)}>Cancelar</Button><Button onClick={() => void saveTaskTemplate()} disabled={saving}>{saving ? "Salvando…" : "Salvar modelo de tarefa"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
